services:
  - type: web
    name: sdnoder
    env: go
    repo: https://github.com/rockynh/sdnoder.git
    buildCommand: "go build -tags netgo -ldflags '-s -w -o sdnoder'"
    startCommand: "./sdnoder -L=$PROTOCOL://$USERPASS@:$PORT"
    envVars:
      - key: PROTOCOL
        value: 'ws'
      - key: USERPASS
        sync: false